name: .NET Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Install .NET Framework Developer Pack
      run: choco install netfx-4.8-devpack

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: OculusKiller
        path: D:\a\OculusKiller\OculusKiller\OculusKiller\bin\x64\Release\OculusDash.exe

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        RELEASE_NAME: Release $(date +%F)
        RELEASE_TAGS: $(date +%F)

    - name: Upload Artifact to Release
      uses: actions/upload-release-asset@v2
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./downloaded-artifacts/OculusKiller/OculusKiller/bin/x64/Release/OculusDash.exe
        asset_name: OculusKiller
        asset_content_type: application/x-msdownload

    - name: Test
      run: dotnet test --no-build --verbosity normal
